# Generated by Django 6.0.5 on 2026-05-26 16:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='e.g. diesel, natural_gas, electricity, flight_short, flight_long, hotel_night, car_diesel, car_petrol, car_electric', max_length=100)),
                ('raw_unit', models.CharField(help_text='Unit we expect from input (e.g. L, Gallon, m3, kWh, MWh, mi, km)', max_length=50)),
                ('normalized_unit', models.CharField(help_text='Base unit (e.g. L, m3, kWh, pkm, room_night)', max_length=50)),
                ('conversion_multiplier', models.DecimalField(decimal_places=6, default=1.0, help_text='Multiply raw quantity by this to get normalized quantity', max_digits=12)),
                ('factor_kg_co2e', models.DecimalField(decimal_places=6, help_text='Emissions factor per normalized unit', max_digits=12)),
                ('region', models.CharField(default='GLOBAL', help_text='e.g. US-CA (California grid), DE (German grid), UK, GLOBAL', max_length=100)),
                ('scope', models.IntegerField(choices=[(1, 'Scope 1'), (2, 'Scope 2'), (3, 'Scope 3')])),
            ],
            options={
                'unique_together': {('category', 'raw_unit', 'region')},
            },
        ),
        migrations.CreateModel(
            name='IngestionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('SAP', 'SAP ERP (Fuel & Procurement)'), ('UTILITY', 'Utility Portal (Electricity)'), ('CONCUR', 'Corporate Travel (Concur/Navan)')], max_length=20)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='RUNNING', max_length=20)),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('summary', models.JSONField(default=dict, help_text='Stores counts: {total, success, failed, suspicious}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_jobs', to='emissions.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('facility_code', models.CharField(help_text='SAP Plant Code or Utility Meter/Account number', max_length=100)),
                ('region', models.CharField(help_text='Used for regional electricity grid factor lookup (e.g. US-CA, US-NY, DE, UK)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='emissions.organization')),
            ],
            options={
                'verbose_name_plural': 'Facilities',
                'unique_together': {('organization', 'facility_code')},
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('CREATE', 'Created Record'), ('UPDATE', 'Updated Value'), ('APPROVE', 'Approved & Locked'), ('REJECT', 'Rejected Record'), ('UNLOCK', 'Unlocked Record')], max_length=20)),
                ('record_type', models.CharField(help_text='RAW_RECORD or NORMALIZED_RECORD', max_length=50)),
                ('record_id', models.IntegerField()),
                ('field_name', models.CharField(blank=True, help_text='Name of the edited field, if applicable', max_length=100, null=True)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('reason', models.TextField(help_text='Justification provided by the analyst')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='emissions.organization')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_index', models.IntegerField(help_text='Line number or sequence index in the source data')),
                ('raw_data', models.JSONField(help_text='Exact raw key-value pairs ingested from source')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUSPICIOUS', 'Suspicious (Requires Verification)')], default='PENDING', max_length=20)),
                ('validation_errors', models.JSONField(blank=True, default=list, help_text='List of validation failures or reasons for suspicious tag')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='emissions.ingestionjob')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='emissions.organization')),
            ],
            options={
                'ordering': ['job', 'row_index'],
            },
        ),
        migrations.CreateModel(
            name='NormalizedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.IntegerField(choices=[(1, 'Scope 1'), (2, 'Scope 2'), (3, 'Scope 3')])),
                ('category', models.CharField(help_text='e.g. Stationary Combustion, Purchased Electricity, Business Travel', max_length=100)),
                ('activity_date', models.DateField(help_text='Normalized transaction date or month-start')),
                ('start_date', models.DateField(blank=True, help_text='Start of billing or activity period', null=True)),
                ('end_date', models.DateField(blank=True, help_text='End of billing or activity period', null=True)),
                ('raw_quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('raw_unit', models.CharField(max_length=50)),
                ('normalized_quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('normalized_unit', models.CharField(help_text='Base unit (e.g. kWh, Liters, Passenger-km)', max_length=50)),
                ('co2e_kg', models.DecimalField(decimal_places=4, max_digits=18)),
                ('calculation_metadata', models.JSONField(default=dict, help_text='Calculated using: formula, emission_factor, source_factor_link')),
                ('is_locked', models.BooleanField(default=False, help_text='Locked once approved. Edits blocked unless unlocked by Admin')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(blank=True, help_text='Mapped plant or facility', null=True, on_delete=django.db.models.deletion.SET_NULL, to='emissions.facility')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_records', to='emissions.organization')),
                ('raw_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_record', to='emissions.rawrecord')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('analyst', 'Analyst'), ('auditor', 'Auditor'), ('admin', 'Admin')], default='analyst', max_length=20)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='emissions.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
